version: "3"
services:
  fe:
    container_name: fe
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - "4400:3000"
    # restart: unless-stopped
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./fe/node_modules:/usr/app/node_modules
      - ./fe:/usr/app
  # nginx:
  #   image: nginx
  #   ports:
  #     - "80:4400"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf